apiVersion: v1
kind: Pod
metadata:
  name: nonstop-pod
spec:
  containers:
    - name: hostname
      image: david8bullet/hostname
      ports:
      - containerPort: 8090
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

